// Seed script for real estate data
// Run with: npx ts-node scripts/seed-data.ts

import { createClient } from '@supabase/supabase-js';

// Get credentials from environment
const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  console.log('Run with: SUPABASE_URL=xxx SUPABASE_SERVICE_ROLE_KEY=xxx npx ts-node scripts/seed-data.ts');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ============ DEVELOPERS DATA ============
const developers = [
  {
    name: 'Vinhomes',
    logo: 'https://vinhomes.vn/themes/flavor/images/logo.svg',
    description: 'Vinhomes là thương hiệu bất động sản hàng đầu Việt Nam, trực thuộc Tập đoàn Vingroup. Được thành lập từ năm 2008, Vinhomes đã phát triển hơn 49 đại đô thị trên toàn quốc với tiêu chuẩn quốc tế.',
    established_year: 2008,
    website: 'https://vinhomes.vn',
    hotline: '1900 2323 89',
    email: 'contact@vinhomes.vn',
    address: 'Số 7, đường Bằng Lăng 1, Phường Việt Hưng, Quận Long Biên, Hà Nội',
    total_projects: 49,
    completed_projects: 35,
    avg_legal_score: 9.5,
    avg_rating: 4.8,
    specialties: ['Đại đô thị', 'Căn hộ cao cấp', 'Biệt thự', 'Shophouse'],
  },
  {
    name: 'Masterise Homes',
    logo: 'https://masterisehomes.com/wp-content/uploads/2020/03/masterise-homes-logo.png',
    description: 'Masterise Homes là nhà phát triển bất động sản hạng sang số 1 Việt Nam, thuộc Masterise Group. Tiền thân là Thảo Điền Investment, công ty nổi tiếng với các dự án căn hộ hàng hiệu mang đẳng cấp quốc tế.',
    established_year: 2007,
    website: 'https://masterisehomes.com',
    hotline: '1800 6868 68',
    email: 'info@masterisehomes.com',
    address: 'Tầng 25, Saigon Centre Tower 2, 67 Lê Lợi, Quận 1, TP.HCM',
    total_projects: 12,
    completed_projects: 6,
    avg_legal_score: 9.2,
    avg_rating: 4.7,
    specialties: ['Căn hộ hạng sang', 'Branded Residence', 'Penthouse', 'Duplex'],
  },
  {
    name: 'Novaland',
    logo: 'https://novaland.com.vn/Data/Sites/1/News/5773/novaland-logo.png',
    description: 'Novaland Group là tập đoàn phát triển bất động sản hàng đầu Việt Nam, được thành lập năm 1992. Công ty đã phát triển nhiều dự án đa dạng từ căn hộ đến biệt thự nghỉ dưỡng trên toàn quốc.',
    established_year: 1992,
    website: 'https://novaland.com.vn',
    hotline: '1800 6789 99',
    email: 'info@novaland.com.vn',
    address: 'Tầng 8, Tòa nhà Citi Tower, 115 Nguyễn Cơ Thạch, Quận 2, TP.HCM',
    total_projects: 45,
    completed_projects: 28,
    avg_legal_score: 7.5,
    avg_rating: 4.2,
    specialties: ['Căn hộ', 'Biệt thự', 'Nghỉ dưỡng', 'Đô thị tích hợp'],
  },
  {
    name: 'Gamuda Land',
    logo: 'https://gamudaland.com.vn/wp-content/uploads/2020/01/gamuda-land-logo.png',
    description: 'Gamuda Land là công ty phát triển bất động sản thuộc Tập đoàn Gamuda Berhad (Malaysia). Tại Việt Nam, Gamuda Land nổi tiếng với các dự án đô thị xanh quy mô lớn như Celadon City và Gamuda Gardens.',
    established_year: 1995,
    website: 'https://gamudaland.com.vn',
    hotline: '1800 599 920',
    email: 'info@gamudaland.com.vn',
    address: 'Tầng 12A, Tòa nhà Centec Tower, 72-74 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
    total_projects: 8,
    completed_projects: 5,
    avg_legal_score: 9.0,
    avg_rating: 4.6,
    specialties: ['Đô thị xanh', 'Căn hộ sinh thái', 'Township', 'TOD'],
  },
  {
    name: 'Sơn Kim Land',
    logo: 'https://sonkimland.com/wp-content/uploads/logo-sonkim.png',
    description: 'Sơn Kim Land là công ty phát triển bất động sản cao cấp tại TP.HCM, thuộc Tập đoàn Sơn Kim Group. Nổi tiếng với các dự án chất lượng cao tại khu vực Thủ Đức như The 9 Stellars.',
    established_year: 2010,
    website: 'https://sonkimland.com',
    hotline: '1900 5858 98',
    email: 'info@sonkimland.com',
    address: '15 Lê Thánh Tôn, Phường Bến Nghé, Quận 1, TP.HCM',
    total_projects: 6,
    completed_projects: 3,
    avg_legal_score: 8.5,
    avg_rating: 4.4,
    specialties: ['Căn hộ cao cấp', 'TOD', 'Mixed-use'],
  },
  {
    name: 'Khang Điền',
    logo: 'https://khangdien.com.vn/wp-content/uploads/logo-khang-dien.png',
    description: 'Nhà Khang Điền (KDH) là một trong những doanh nghiệp bất động sản uy tín nhất Việt Nam, chuyên phát triển các khu đô thị và nhà ở tại khu vực phía Đông TP.HCM.',
    established_year: 2001,
    website: 'https://khangdien.com.vn',
    hotline: '1800 6868 02',
    email: 'info@khangdien.com.vn',
    address: '57 Đường số 3, Khu phố 4, Phường An Khánh, TP. Thủ Đức, TP.HCM',
    total_projects: 15,
    completed_projects: 12,
    avg_legal_score: 9.3,
    avg_rating: 4.7,
    specialties: ['Nhà phố', 'Biệt thự', 'Căn hộ', 'Khu đô thị'],
  },
  {
    name: 'Phú Mỹ Hưng',
    logo: 'https://phumyhung.vn/wp-content/uploads/logo-phu-my-hung.png',
    description: 'Phú Mỹ Hưng là nhà phát triển đô thị tiên phong tại Việt Nam, đã biến vùng đất hoang sơ phía Nam Sài Gòn thành khu đô thị kiểu mẫu đạt chuẩn quốc tế.',
    established_year: 1993,
    website: 'https://phumyhung.vn',
    hotline: '028 5411 9999',
    email: 'info@phumyhung.vn',
    address: 'Tầng 10, Tòa nhà Lawrence S.Ting, 801 Nguyễn Văn Linh, Quận 7, TP.HCM',
    total_projects: 25,
    completed_projects: 22,
    avg_legal_score: 9.8,
    avg_rating: 4.9,
    specialties: ['Khu đô thị', 'Căn hộ cao cấp', 'Biệt thự', 'Văn phòng'],
  },
  {
    name: 'Capitaland',
    logo: 'https://capitaland.com/content/dam/capitaland-sites/international/about-capitaland/our-brand/capitaland-logo.png',
    description: 'CapitaLand là một trong những tập đoàn bất động sản đa dạng hóa lớn nhất châu Á, có trụ sở tại Singapore. Tại Việt Nam, CapitaLand nổi tiếng với các dự án căn hộ cao cấp.',
    established_year: 2000,
    website: 'https://capitaland.com',
    hotline: '028 3821 8888',
    email: 'vietnam@capitaland.com',
    address: 'Tầng 29, Bitexco Financial Tower, 2 Hải Triều, Quận 1, TP.HCM',
    total_projects: 10,
    completed_projects: 8,
    avg_legal_score: 9.5,
    avg_rating: 4.6,
    specialties: ['Căn hộ cao cấp', 'Commercial', 'Retail', 'Integrated Development'],
  },
];

// ============ PROJECTS DATA ============
const projects = [
  // Vinhomes Projects
  {
    name: 'Vinhomes Grand Park',
    developer: 'Vinhomes',
    location: '128 Nguyễn Xiển, Phường Long Thạnh Mỹ, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'Vinhomes Grand Park là đại đô thị đẳng cấp quốc tế đầu tiên tại TP.HCM, với quy mô 271ha, tích hợp đầy đủ tiện ích như công viên 36ha, biển hồ nhân tạo, trung tâm thương mại Vincom Mega Mall.',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    price_per_sqm: 55000000,
    price_range: '2.5 - 15 tỷ',
    legal_score: 9.5,
    status: 'Đang mở bán',
    total_units: 44000,
    sold_units: 38000,
    floors: 45,
    launch_date: '2019-09-01',
    completion_date: '2024-12-01',
    amenities: ['Hồ bơi', 'Gym', 'Công viên 36ha', 'Vincom Mega Mall', 'Trường học Vinschool', 'Bệnh viện Vinmec'],
    apartment_types: ['Studio', '1PN', '2PN', '3PN', 'Penthouse'],
  },
  {
    name: 'The Opus One',
    developer: 'Vinhomes',
    location: 'Vinhomes Grand Park, Phường Long Thạnh Mỹ, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'The Opus One là phân khu căn hộ cao cấp hợp tác với SAMTY Nhật Bản, mang đến không gian sống chuẩn Nhật với thiết kế tối ưu và chất lượng xây dựng đẳng cấp.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    price_per_sqm: 75000000,
    price_range: '3.5 - 8 tỷ',
    legal_score: 9.5,
    status: 'Đang mở bán',
    total_units: 2500,
    sold_units: 1200,
    floors: 35,
    launch_date: '2024-02-01',
    completion_date: '2026-03-01',
    amenities: ['Hồ bơi Nhật Bản', 'Onsen', 'Gym', 'Sky Garden', 'Co-working space'],
    apartment_types: ['1PN', '2PN', '3PN'],
  },
  {
    name: 'The Beverly',
    developer: 'Vinhomes',
    location: 'Vinhomes Grand Park, Phường Long Bình, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'The Beverly là phân khu căn hộ phong cách Beverly Hills với thiết kế sang trọng, view trực diện công viên 36ha và biển hồ nhân tạo.',
    image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
    price_per_sqm: 50000000,
    price_range: '1.6 - 15 tỷ',
    legal_score: 9.5,
    status: 'Đang mở bán',
    total_units: 5000,
    sold_units: 4200,
    floors: 32,
    launch_date: '2022-06-01',
    completion_date: '2025-06-01',
    amenities: ['Hồ bơi vô cực', 'Clubhouse', 'BBQ Garden', 'Kids playground', 'Tennis court'],
    apartment_types: ['Studio', '1PN', '2PN', '3PN', 'Duplex'],
  },
  {
    name: 'Glory Heights',
    developer: 'Vinhomes',
    location: 'Vinhomes Grand Park, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'Glory Heights là phân khu căn hộ ultra-premium với thiết kế full LED sang trọng, tiện ích chuẩn resort 5 sao, vị trí liền kề Vincom Mega Mall.',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    price_per_sqm: 85000000,
    price_range: '5 - 20 tỷ',
    legal_score: 9.5,
    status: 'Đang mở bán',
    total_units: 1800,
    sold_units: 600,
    floors: 40,
    launch_date: '2024-09-01',
    completion_date: '2027-06-01',
    amenities: ['Sky Pool', 'Cigar Lounge', 'Private Cinema', 'Spa & Wellness', 'Concierge 24/7'],
    apartment_types: ['2PN', '3PN', '4PN', 'Penthouse', 'Sky Villa'],
  },

  // Masterise Homes Projects
  {
    name: 'Lumiere Boulevard',
    developer: 'Masterise Homes',
    location: 'Vinhomes Grand Park, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'Lumiere Boulevard là tổ hợp căn hộ cao cấp mang thương hiệu Lumiere, với vị trí đắc địa kế bên công viên 36ha và biển hồ nhân tạo của Vinhomes Grand Park.',
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800',
    price_per_sqm: 70000000,
    price_range: '3 - 12 tỷ',
    legal_score: 9.2,
    status: 'Đang mở bán',
    total_units: 2422,
    sold_units: 1800,
    floors: 39,
    launch_date: '2021-11-01',
    completion_date: '2025-03-01',
    amenities: ['Hồ bơi tràn viền', 'Sky Lounge', 'Yoga Deck', 'Smart Home', 'Concierge'],
    apartment_types: ['1PN', '2PN', '3PN', 'Penthouse'],
  },
  {
    name: 'The Global City',
    developer: 'Masterise Homes',
    location: 'An Phú, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'The Global City là khu Downtown sang trọng & hiện đại bậc nhất TP. Thủ Đức, được phát triển với đối tác Foster + Partners - kiến trúc sư hàng đầu thế giới.',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
    price_per_sqm: 160000000,
    price_range: '10 - 50 tỷ',
    legal_score: 9.0,
    status: 'Sắp mở bán',
    total_units: 8000,
    sold_units: 0,
    floors: 50,
    launch_date: '2025-06-01',
    completion_date: '2029-12-01',
    amenities: ['Kênh đào Venice', 'Marina', 'Helipad', 'Private Club', 'International School'],
    apartment_types: ['2PN', '3PN', '4PN', 'Penthouse', 'Branded Residence'],
  },
  {
    name: 'Masteri Grand View',
    developer: 'Masterise Homes',
    location: 'The Global City, An Phú, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'Masteri Grand View là phân khu căn hộ đầu tiên của The Global City với 27 tòa tháp nằm dọc theo kênh đào, mang đến tầm view đẳng cấp.',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    price_per_sqm: 140000000,
    price_range: '8 - 30 tỷ',
    legal_score: 9.0,
    status: 'Đang mở bán',
    total_units: 3000,
    sold_units: 500,
    floors: 45,
    launch_date: '2024-12-01',
    completion_date: '2028-06-01',
    amenities: ['Canal View', 'Infinity Pool', 'Sky Garden', 'Premium Gym', 'Co-living Space'],
    apartment_types: ['1PN', '2PN', '3PN', 'Duplex'],
  },
  {
    name: 'One Central Saigon',
    developer: 'Masterise Homes',
    location: 'Khu tứ giác Bến Thành, Quận 1',
    district: 'Quận 1',
    city: 'Hồ Chí Minh',
    description: 'One Central Saigon là biểu tượng danh giá tại khu tứ giác Chợ Bến Thành - trung tâm đắt địa nhất Quận 1, phát triển bởi Masterise Homes.',
    image: 'https://images.unsplash.com/photo-1524813686514-a57563d77965?w=800',
    price_per_sqm: 350000000,
    price_range: '30 - 150 tỷ',
    legal_score: 9.3,
    status: 'Sắp mở bán',
    total_units: 500,
    sold_units: 0,
    floors: 55,
    launch_date: '2025-09-01',
    completion_date: '2029-12-01',
    amenities: ['Rooftop Bar', 'Michelin Restaurant', 'Spa Retreat', 'Art Gallery', 'Valet Parking'],
    apartment_types: ['2PN', '3PN', '4PN', 'Penthouse', 'Super Penthouse'],
  },

  // Novaland Projects
  {
    name: 'The Grand Manhattan',
    developer: 'Novaland',
    location: '100 Cô Giang, Phường Cô Giang, Quận 1',
    district: 'Quận 1',
    city: 'Hồ Chí Minh',
    description: 'The Grand Manhattan là dự án căn hộ hạng sang tại trung tâm Quận 1, gần Chợ Bến Thành và Công viên 23/9, đã hoàn thành cất nóc.',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    price_per_sqm: 180000000,
    price_range: '15 - 80 tỷ',
    legal_score: 7.5,
    status: 'Đang xây dựng',
    total_units: 1000,
    sold_units: 750,
    floors: 40,
    launch_date: '2019-03-01',
    completion_date: '2025-12-01',
    amenities: ['Rooftop Pool', 'Sky Garden', 'Premium Lobby', 'Smart Parking', 'Concierge'],
    apartment_types: ['1PN', '2PN', '3PN', 'Penthouse'],
  },
  {
    name: 'The Sun Avenue',
    developer: 'Novaland',
    location: '28 Mai Chí Thọ, Phường An Phú, Quận 2',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'The Sun Avenue là khu căn hộ cao cấp tại mặt tiền Mai Chí Thọ, gần Metro và các tiện ích thương mại sầm uất.',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    price_per_sqm: 65000000,
    price_range: '3 - 8 tỷ',
    legal_score: 8.0,
    status: 'Đã bàn giao',
    total_units: 1800,
    sold_units: 1800,
    floors: 28,
    launch_date: '2016-09-01',
    completion_date: '2020-06-01',
    amenities: ['Hồ bơi', 'Gym', 'Sân tennis', 'BBQ', 'Khu vui chơi trẻ em'],
    apartment_types: ['1PN', '2PN', '3PN'],
  },
  {
    name: 'Kingston Residence',
    developer: 'Novaland',
    location: '146 Nguyễn Văn Trỗi, Phường 8, Quận Phú Nhuận',
    district: 'Phú Nhuận',
    city: 'Hồ Chí Minh',
    description: 'Kingston Residence là dự án căn hộ cao cấp tại trung tâm Phú Nhuận, gần sân bay Tân Sơn Nhất với thiết kế hiện đại.',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    price_per_sqm: 80000000,
    price_range: '5 - 12 tỷ',
    legal_score: 8.5,
    status: 'Đã bàn giao',
    total_units: 250,
    sold_units: 250,
    floors: 25,
    launch_date: '2017-06-01',
    completion_date: '2020-12-01',
    amenities: ['Hồ bơi tầng thượng', 'Gym', 'Sauna', 'Sky Lounge', 'Hầm xe thông minh'],
    apartment_types: ['2PN', '3PN', 'Penthouse'],
  },

  // Gamuda Land Projects
  {
    name: 'Celadon City',
    developer: 'Gamuda Land',
    location: 'Đường Nguyễn Hữu Thọ, Phường Sơn Kỳ, Quận Tân Phú',
    district: 'Tân Phú',
    city: 'Hồ Chí Minh',
    description: 'Celadon City là khu đô thị xanh đẳng cấp với hơn 16ha cây xanh và mặt nước, được Gamuda Land phát triển theo tiêu chuẩn Malaysia.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    price_per_sqm: 75000000,
    price_range: '4.9 - 7.9 tỷ',
    legal_score: 9.0,
    status: 'Đang mở bán',
    total_units: 6000,
    sold_units: 4500,
    floors: 35,
    launch_date: '2010-01-01',
    completion_date: '2025-12-01',
    amenities: ['Hồ cảnh quan 3.2ha', 'Công viên trung tâm', 'Aeon Mall', 'Trường quốc tế', 'Gym'],
    apartment_types: ['1PN', '2PN', '3PN', 'Duplex'],
  },
  {
    name: 'Eaton Park',
    developer: 'Gamuda Land',
    location: 'Mai Chí Thọ, Phường An Phú, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'Eaton Park là dự án căn hộ cao cấp ngay mặt tiền Mai Chí Thọ với view sông Sài Gòn, được Gamuda Land nhận chuyển nhượng và phát triển.',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    price_per_sqm: 120000000,
    price_range: '6 - 15 tỷ',
    legal_score: 8.8,
    status: 'Đang mở bán',
    total_units: 1200,
    sold_units: 400,
    floors: 40,
    launch_date: '2024-03-01',
    completion_date: '2027-06-01',
    amenities: ['River View', 'Infinity Pool', 'Sky Garden', 'Tennis Court', 'Jogging Track'],
    apartment_types: ['1PN', '2PN', '3PN', 'Penthouse'],
  },

  // Sơn Kim Land Projects
  {
    name: 'The 9 Stellars',
    developer: 'Sơn Kim Land',
    location: 'Xa lộ Hà Nội, Phường Long Bình, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'The 9 Stellars là khu đô thị TOD đầu tiên tại TP.HCM, nằm ngay điểm cuối Metro Bến Thành - Suối Tiên, kết nối hoàn hảo giao thông công cộng.',
    image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800',
    price_per_sqm: 65000000,
    price_range: '3 - 10 tỷ',
    legal_score: 8.5,
    status: 'Đang mở bán',
    total_units: 3500,
    sold_units: 1500,
    floors: 30,
    launch_date: '2023-06-01',
    completion_date: '2026-12-01',
    amenities: ['Ga Metro', 'Shopping Mall', 'Hồ bơi', 'Gym', 'Công viên 5ha'],
    apartment_types: ['Studio', '1PN', '2PN', '3PN'],
  },

  // Khang Điền Projects
  {
    name: 'The Privia',
    developer: 'Khang Điền',
    location: 'Đường Nguyễn Duy Trinh, Phường Long Trường, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'The Privia là khu căn hộ cao cấp thuộc khu đô thị Khang Điền, với thiết kế xanh và tiện ích đồng bộ.',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    price_per_sqm: 55000000,
    price_range: '2.5 - 6 tỷ',
    legal_score: 9.3,
    status: 'Đang mở bán',
    total_units: 1500,
    sold_units: 800,
    floors: 25,
    launch_date: '2024-01-01',
    completion_date: '2026-06-01',
    amenities: ['Hồ bơi', 'Gym', 'Công viên nội khu', 'Trường học', 'TTTM'],
    apartment_types: ['1PN', '2PN', '3PN'],
  },

  // Phú Mỹ Hưng Projects
  {
    name: 'The Antonia',
    developer: 'Phú Mỹ Hưng',
    location: 'Khu đô thị Phú Mỹ Hưng, Quận 7',
    district: 'Quận 7',
    city: 'Hồ Chí Minh',
    description: 'The Antonia là căn hộ cao cấp tại trung tâm Phú Mỹ Hưng với thiết kế sang trọng và view công viên.',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    price_per_sqm: 90000000,
    price_range: '6 - 18 tỷ',
    legal_score: 9.8,
    status: 'Đang mở bán',
    total_units: 600,
    sold_units: 350,
    floors: 30,
    launch_date: '2023-09-01',
    completion_date: '2026-03-01',
    amenities: ['Club House', 'Hồ bơi', 'Gym', 'Sân tennis', 'Vườn BBQ'],
    apartment_types: ['2PN', '3PN', '4PN', 'Penthouse'],
  },
  {
    name: 'The Peak Midtown',
    developer: 'Phú Mỹ Hưng',
    location: 'Midtown Phú Mỹ Hưng, Quận 7',
    district: 'Quận 7',
    city: 'Hồ Chí Minh',
    description: 'The Peak Midtown là tháp căn hộ biểu tượng của Midtown với view panorama toàn cảnh Phú Mỹ Hưng.',
    image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800',
    price_per_sqm: 100000000,
    price_range: '8 - 25 tỷ',
    legal_score: 9.8,
    status: 'Đã bàn giao',
    total_units: 450,
    sold_units: 450,
    floors: 35,
    launch_date: '2019-06-01',
    completion_date: '2022-12-01',
    amenities: ['Sky Lounge', 'Hồ bơi vô cực', 'Gym cao cấp', 'Spa', 'Sân golf mini'],
    apartment_types: ['2PN', '3PN', 'Penthouse'],
  },

  // CapitaLand Projects
  {
    name: 'Feliz en Vista',
    developer: 'Capitaland',
    location: 'Song Hành, Phường An Phú, TP. Thủ Đức',
    district: 'Thủ Đức',
    city: 'Hồ Chí Minh',
    description: 'Feliz en Vista là dự án căn hộ cao cấp view sông Sài Gòn, được CapitaLand phát triển với chất lượng Singapore.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    price_per_sqm: 75000000,
    price_range: '4 - 12 tỷ',
    legal_score: 9.5,
    status: 'Đã bàn giao',
    total_units: 1100,
    sold_units: 1100,
    floors: 36,
    launch_date: '2016-03-01',
    completion_date: '2020-06-01',
    amenities: ['Hồ bơi', 'Gym', 'Tennis', 'BBQ', 'Sân chơi trẻ em', 'Jogging track'],
    apartment_types: ['1PN', '2PN', '3PN', 'Duplex', 'Penthouse'],
  },
];

// ============ SEED FUNCTIONS ============

async function seedDevelopers() {
  console.log('🏗️ Seeding developers...');

  for (const dev of developers) {
    const { error } = await supabase.from('developers').upsert(dev, {
      onConflict: 'name',
    });

    if (error) {
      console.error(`❌ Error inserting ${dev.name}:`, error.message);
    } else {
      console.log(`✅ Inserted/Updated: ${dev.name}`);
    }
  }
}

async function seedProjects() {
  console.log('🏢 Seeding projects...');

  for (const project of projects) {
    // Map field names to database column names
    const dbProject = {
      name: project.name,
      developer: project.developer,
      location: project.location,
      district: project.district,
      city: project.city,
      description: project.description,
      image: project.image,
      price_per_sqm: project.price_per_sqm,
      price_range: project.price_range,
      legal_score: project.legal_score,
      status: project.status,
      total_units: project.total_units,
      sold_units: project.sold_units,
      floors: project.floors,
      launch_date: project.launch_date,
      completion_date: project.completion_date,
      amenities: project.amenities,
      apartment_types: project.apartment_types,
    };

    const { error } = await supabase.from('projects').upsert(dbProject, {
      onConflict: 'name',
    });

    if (error) {
      console.error(`❌ Error inserting ${project.name}:`, error.message);
    } else {
      console.log(`✅ Inserted/Updated: ${project.name}`);
    }
  }
}

async function main() {
  console.log('🚀 Starting seed process...\n');

  try {
    await seedDevelopers();
    console.log('\n');
    await seedProjects();
    console.log('\n✨ Seed completed successfully!');
  } catch (error) {
    console.error('💥 Seed failed:', error);
    process.exit(1);
  }
}

main();
