// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybjuvbpnlwdccveyclmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlianV2YnBubHdkY2N2ZXljbG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTAyOTksImV4cCI6MjA2OTkyNjI5OX0.lLg7VgGUkL7P0lg-odsyD7LR3l1mlqHKLZOVQeK8Cws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});